version: '3.9'

services:
  db:
    image: postgres:15
    container_name: marcelo_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    ports:
      - "5433:5433"
    networks:
      - backend

  web:
    build: .
    container_name: marcelo_fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data: